---

server:
  port: 8081
 
spring:
  data:
    mongodb:
#      host: mongo
      host: 192.168.1.210
      port: 27017
      database: BillsBars
---
  
spring: 
  profiles: dev
  data: 
    mongodb: 
      host: 192.168.1.210
      port: 27017 
      database: BillsBars


---



