---

server:
  port: 8081
 
spring:
  data:
    mongodb:
      host: mongo
      port: 27017
      database: BillsBars
      
---
  
spring: 
  profiles:
    active: dev
  data: 
    mongodb: 
      host: 172.17.0.2
      port: 27017 
      database: BillsBars


---

spring: 
  profiles: test
  data: 
    mongodb: 
      host: 172.17.0.2
      port: 27017 
      database: TestBillsBars



