package com.billsbars.app.model;

public enum BaseScents {
	NONE,
	BLUEBERRY_COBBLER,
	VANILLA,
	APPLE_BLOSSOM,
	PINK_GRAPEFRUIT,
	BLACK_RAPBERRY_VANILLA,
	COOL_WATER,
	LAVENDER,
	BLOOD_ORANGE_GOJI_BERRY,
	COCONUT_WATER_AND_MANGO,
	THOUSAND_WISHES,
	BLACK_AMBER_AND_LAVENDER,
	CERULIAN_SKIES_AND_PINE,
	COCONUT_ORCHIDE,
	CUCUMBER_MELON
	

}
